# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f1a0f9a603dc992bca073f881aa8c668a92b4611c55fa92eecd631999e62236039563884a985d8ff16755082df145c76a5e6d5064f0e8975c7c4436e429b570

test:
  secret_key_base: 43e223e7f561389877912e5a1eb08d42d14d73c1c517dbeac5e7d706bd55084e3c60842730452df139e8989dae177bc2b040f0aad4fbea58e032d78da46f7380

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
